#!/bin/bash

set -e -u -x

vboxmanage setextradata "$1" VBoxInternal/Devices/buslogic/0/Config/AdapterType "AHA-1540B"
vboxmanage setextradata "$1" VBoxInternal/Devices/buslogic/0/Config/ISACompat "Primary" # use io address 0x330 instead of 0x334

vboxmanage modifyvm "$1" --nictype1=wd8013
vboxmanage setextradata "$1" VBoxInternal/Devices/dp8390/0/Config/IRQ 5
# default resource settings are otherwise the ones we need


