#!/bin/sh
set -e
set -u

existing=`pkginfo | grep GNUgcc | awk '{print $2}'`

device=/home/dell/pkg
pkgarchive=/home3/pkgfiles

if [ $# -lt 1 ]; then
	echo "Usage:"
	echo " $0 {3.0.4|3.4.6}"
	exit 1
fi

set -x

ver="$1"
case $ver in \
	3.0.4)
		target=GNUgcc304
		device=$pkgarchive/$target.pkg
		;;
	3.4.6)
		target=GNUgcc346
		;;
	*)
		set +x
		echo "Unknown ver $ver"
		exit 1
		;;
esac

if [ "$existing" != "$target" ]; then
	for pkg in $existing; do
		pkgrm -n $pkg
	done
	pkgadd -d $device $target
fi


